#cloud-config
runcmd:
  - apt update && apt install -y python3-pip python3-venv git docker.io
  - G_TOKEN="..."
  - REPO_NAME="Stage10-docker-conatiner/project"
  - KEY_VAULT_NAME="chatbot5-keyvault"
  - USERNAME="azureuser"

  - echo "export GITHUB_TOKEN=$G_TOKEN" >> /home/$USERNAME/.bashrc
  - echo "export GITHUB_TOKEN=$G_TOKEN" | sudo tee -a /root/.bashrc
  - chown $USERNAME:$USERNAME /home/$USERNAME/.bashrc

  # Allow azureuser to use Docker without sudo
  - usermod -aG docker $USERNAME

  # Run all following commands as azureuser
  - sudo -u $USERNAME bash -c "
      cd /home/$USERNAME &&
      git clone -b main https://$G_TOKEN@github.com/mfldosari/Stage10-docker-conatiner.git &&
      cd $REPO_NAME &&

      echo "KEY_VAULT_NAME=chatbot5-keyvault" > .env &&

      python3 -m venv myenv &&
      source myenv/bin/activate &&
      pip install --upgrade pip &&
      pip install -r requirements.vm.txt
    "

  # Create ChromaDB systemd service using Docker
  - |
    cat <<EOF | sudo tee /etc/systemd/system/chromadb.service
    [Unit]
    Description=ChromaDB via Docker
    After=docker.service
    Requires=docker.service

    [Service]
    Restart=always
    ExecStartPre=-/usr/bin/docker rm -f chromadb
    ExecStart=/usr/bin/docker run --name chromadb -p 8000:8000 -e CHROMA_SERVER_HOST=0.0.0.0 ghcr.io/chroma-core/chroma:0.4.24
    ExecStop=/usr/bin/docker stop chromadb

    [Install]
    WantedBy=multi-user.target
    EOF

  # Create Streamlit systemd service
  - |
    cat <<EOF | sudo tee /etc/systemd/system/frontend.service
    [Unit]
    Description=Streamlit
    After=network.target

    [Service]
    Type=simple
    User=$USERNAME 
    WorkingDirectory=/home/$USERNAME/$REPO_NAME
    ExecStart=/home/$USERNAME/$REPO_NAME/myenv/bin/streamlit run chatbot.py
    Restart=always

    [Install]
    WantedBy=multi-user.target
    EOF

  # Reload and start services
  - sudo systemctl daemon-reload
  - sudo systemctl enable chromadb && sudo systemctl start chromadb
  - sudo systemctl enable frontend && sudo systemctl start frontend
